version: '3.7'

services:

  sample-prod:
    container_name: notablog-hyphen-sop-app-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '1337:80'
    command:
      node --experimental-lexer start